language: php
php:
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - pecl channel-update pecl.php.net
  - pecl install yaml-beta < /dev/null
  - echo "extension=yaml.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev -o --prefer-source --no-interaction
  - chmod +x bin/install-phalcon.sh
  - bin/install-phalcon.sh 3.0.x

before_script:
  - mysql -uroot -e "create database admin"
  - mysql -uroot -e "create database user1"
  - mysql -uroot -e "create database user2"
  - mysql -uroot -e "create database common"
  - mysql -uroot -e "use admin;  create table admin_user (`id` int(11) AUTO_INCREMENT, `admin_config_db_id` tinyint(4))"
  - mysql -uroot -e "use admin;  create table admin_config_db (`id` int(11) AUTO_INCREMENT, `name` varchar(50), `gravity` tinyint(4))"
  - mysql -uroot -e "use user1;  create table user (`id` int(11), `name` varchar(50))"
  - mysql -uroot -e "use user2;  create table user (`id` int(11), `name` varchar(50))"
  - mysql -uroot -e "use common; create table mst_item (`id` int(11) AUTO_INCREMENT, `name` varchar(50))"

script:
  - php -r "echo \Phalcon\Version::get();"
  - vendor/bin/phpunit

addons:
  apt:
    packages:
      - libyaml-dev

services:
  - redis-server
  - mysql